overrides:
  -
    files:
      - '**/*.svelte'
    processor: svelte3/svelte3
    rules:
      brace-style: off
      import/no-unresolved: off # svelte components not found
      no-invalid-this: off
      no-new: off
      node/no-missing-import: off # svelte components not found
plugins:
  - svelte3
